config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
  }

  resources :training_areas
  resources :exercises
  resources :goals
  resources :workouts
  resources :training_periods, path: 'periodization'

  get '/calendar' => 'training#calendar', as: :training_calendar
  get '/motivate' => 'training#motivate', as: :training_motivation
  get '/training' => 'training#index', as: :training
  get '/training/stats' => 'training#stats', as: :training_stats
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user
  has_many :workout_exercises, dependent: :destroy
  has_many :training_area_points, dependent: :destroy

  default_scope { order(date: :asc) }

  validates :user_id, :date, presence: true

  def add_exercises
    user.exercises.each do |exercise|
      self.workout_exercises.find_or_initialize_by(exercise: exercise)
    end
  end

  def add_training_area_points
    user.training_areas.each do |training_area|
      self.training_area_points.find_or_initialize_by(training_area: training_area)
    end
  end

  def past?
    (self.date <= Date.today)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html
  layout :choose_layout

  def index
    @workouts = current_user.workouts
  end

  def show
    @workout.add_exercises
    @workout.add_training_area_points
    @workout.decorate
  end

  def new
    @workout = Workout.new
    @workout.date = Date.parse(params[:date]) if params[:date]
  end

  def edit
  end

  def create
    @workout = Workout.new(workout_params)
    @workout.save
    respond_with @workout, location: -> { workouts_path }
  end

  def update
    workout_form = WorkoutForm.new(params, @workout)
    workout_form.save
    unless request.xhr?
      redirect_to workouts_path
    else
      head :ok
    end
  end

  def destroy
    @workout.destroy
    respond_with @workout, location: -> { workouts_path }
  end

  private

  def choose_layout
    if request.xhr?
      false
    else
      'application'
    end
  end

  def set_workout
    @workout = Workout.find_or_create_by(user: current_user, date: params[:id]).decorate
  end

  def workout_params
    params.require(:workout).permit(
      :date,
      :motivation_level,
      :energy_level
    ).merge(
      user: current_user,
    )
  end
end

app/views/workouts/_exercise.html.slim
.exercise{class="#{exercise.slug} #{exercise.new_record? ? 'hidden' : ''}" id=exercise.slug data-trainingareas=exercise.training_area_slugs.join(' ')}
  h2
    = exercise.name
    i.fa.fa-close[data-role="remove"]

  - begin
    = render partial: "exercise_log_#{exercise.template_name}", locals: { exercise: exercise }
  - rescue ActionView::MissingTemplate => e
    span.hidden= e.path
  - rescue => e
    pre= e

  = text_area_tag :comments, exercise.comments, placeholder: 'Comments'

app/views/workouts/_exercise_log_arc.html.slim
p
  = number_field_tag :number_of_sets, exercise.number_of_sets, placeholder: 'Number of sets'

app/views/workouts/_exercise_log_climbing.html.slim
p
  = number_field_tag :number_of_sets, exercise.number_of_sets, placeholder: 'Number of burns'

p
  = text_field_tag :location, exercise.location, placeholder: 'Sector'

app/views/workouts/_exercise_log_running.html.slim
p
  = number_field_tag :distance, exercise.distance, placeholder: 'Total Distance'

app/views/workouts/_form.html.slim
= simple_form_for(@workout) do |f|
  = f.error_notification

  .form-inputs
    = f.input :motivation_level
    = f.input :energy_level

  .form-actions
    = f.button :submit

app/views/workouts/_slider.html.slim
.slider-container
  span.value= value
  .slider{id=id data-value=value}

app/views/workouts/_training_area_point.html.slim
.training-area-point{class="#{training_area_point.new_record? ? 'hidden' : ''}" id=training_area_point.training_area_slug}
  h2 #{training_area_point.training_area_name} Points
  == render partial: 'slider', locals: { id: training_area_point.training_area_slug, value: training_area_point.points.to_i }

app/views/workouts/edit.html.slim
h1 Editing workout

== render 'form'

= link_to 'Show', @workout
'|
= link_to 'Back', workouts_path

app/views/workouts/index.html.slim
h1 Listing workouts

table
  thead
    tr
      th Date
      th Motivation level
      th Energy level
      th
      th
      th

  tbody
    - @workouts.each do |workout|
      tr
        td = workout.date
        td = workout.motivation_level
        td = workout.energy_level
        td = link_to 'Show', workout
        td = link_to 'Edit', edit_workout_path(workout)
        td = link_to 'Destroy', workout, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Workout', new_workout_path

app/views/workouts/new.html.slim
== render 'form'

app/views/workouts/show.html.slim
.workout[data-url=workout_path(id: @workout.date) class=(@workout.past? ? 'past' : 'future')]
  h1= time_tag @workout.date

  p
    strong Log Exercise
    = select_tag :exercise, options_from_collection_for_select(current_user.exercises, :slug, :name), prompt: @workout.log_exercise_prompt

  .exercises
    - @workout.workout_exercises.each do |exercise|
      == render partial: 'exercise', locals: { exercise: exercise.decorate }

  .points
    .training-area-points
      - @workout.training_area_points.each do |training_area_point|
        == render partial: 'training_area_point', locals: { training_area_point: training_area_point }

    .workout-point
      h2 Motivation level:
      == render partial: 'slider', locals: { id: 'motivation_level', value: @workout.motivation_level.to_i }

    .workout-point
      h2 Energy level:
      == render partial: 'slider', locals: { id: 'energy_level', value: @workout.energy_level.to_i }

  a.button[href='#' data-role="save-workout"]
    span.normal Save Workout
    span.spinner
      i.fa.fa-spinner.fa-spin.spinner

  a.button[href='#' data-role="close-workout"] Close

coffee:
  $ ->
    for i in $('.slider')
      console.log($(i))
      console.log($(i).data().value)
      value = parseInt($(i).data().value)
      console.log "is #{value}"
      $(i).slider
        range: 'max'
        min: 0
        max: 10
        value: value
        slide: (e, ui) ->
          $(@).parents('.slider-container').find('.value').text(ui.value)