config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
  }

  resources :training_areas
  resources :exercises
  resources :goals
  resources :workouts
  resources :training_periods, path: 'periodization'

  get '/calendar' => 'training#calendar', as: :training_calendar
  get '/motivate' => 'training#motivate', as: :training_motivation
  get '/training' => 'training#index', as: :training
  get '/training/stats' => 'training#stats', as: :training_stats
end

app/models/training_area.rb
class TrainingArea < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: [ :slugged, :finders ]

  belongs_to :user
  has_and_belongs_to_many :exercises

  validates :slug, presence: true

  delegate :slug, to: :user, prefix: true, allow_nil: true

  def self.global
    TrainingArea.where(user: nil).all
  end

  private

  def slug_candidates
    [
      [ :name ],
      [ :user_slug, :name, ],
    ]
  end
end

app/controllers/training_areas_controller.rb
class TrainingAreasController < ApplicationController
  before_action :set_training_area, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @training_areas = current_user.training_areas
  end

  def show
  end

  def new
    @training_area = TrainingArea.new
  end

  def edit
  end

  def create
    @training_area = TrainingArea.new(training_area_params)
    @training_area.save
    respond_with @training_area, location: -> { training_areas_path }
  end

  def update
    @training_area.update(training_area_params)
    respond_with @training_area, location: -> { training_areas_path }
  end

  def destroy
    @training_area.destroy
    respond_with @training_area, location: -> { training_areas_path }
  end

  private

  def set_training_area
    @training_area = TrainingArea.find(params[:id])
  end

  def training_area_params
    params.require(:training_area).permit(
      :name,
      :description,
    ).merge(
      user: current_user,
    )
  end
end

app/views/training_areas/_form.html.slim
= simple_form_for(@training_area) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/training_areas/edit.html.slim
h1 Editing training area

== render 'form'

= link_to 'Show', @training_area
'|
= link_to 'Back', training_areas_path

app/views/training_areas/index.html.slim
h1 Training Areas

p What are your overall areas of training?

table
  thead
    tr
      th Name
      th Description
      th Exercises
      th

  tbody
    - @training_areas.each do |training_area|
      tr
        td= training_area.name
        td= simple_format training_area.description
        td
          ul
            - training_area.exercises.each do |exercise|
              li= link_to exercise.name, exercise_path(exercise)
        td
          = link_to 'Edit', edit_training_area_path(training_area), class: 'button'
          = link_to 'Destroy', training_area, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'button'

br

= link_to 'New Training area', new_training_area_path, class: 'button'

app/views/training_areas/new.html.slim
h1 New training_area

== render 'form'

= link_to 'Back', training_areas_path

app/views/training_areas/show.html.slim
p#notice = notice


= link_to 'Edit', edit_training_area_path(@training_area)
'|
= link_to 'Back', training_areas_path