config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
  }

  resources :training_areas
  resources :exercises
  resources :goals
  resources :workouts
  resources :training_periods, path: 'periodization'

  get '/calendar' => 'training#calendar', as: :training_calendar
  get '/motivate' => 'training#motivate', as: :training_motivation
  get '/training' => 'training#index', as: :training
  get '/training/stats' => 'training#stats', as: :training_stats
end

app/models/training_period.rb
class TrainingPeriod < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :name, :start, :finish, :color, presence: true
end

app/controllers/training_periods_controller.rb
class TrainingPeriodsController < ApplicationController
  before_action :set_training_period, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @training_periods = current_user.training_periods
  end

  def show
  end

  def new
    @training_period = TrainingPeriod.new
  end

  def edit
  end

  def create
    @training_period = TrainingPeriod.new(training_period_params)
    @training_period.save

    respond_with @training_period, location: -> { training_periods_path }
  end

  def update
    @training_period.update(training_period_params)
    respond_with @training_period, location: -> { training_periods_path }
  end

  def destroy
    @training_period.destroy
    respond_to do |format|
      format.html { redirect_to training_periods_url, notice: 'Training period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_training_period
    @training_period = TrainingPeriod.find(params[:id])
  end

  def training_period_params
    params.require(:training_period).permit(
      :name,
      :start,
      :finish,
      :color,
    ).merge(
      user: current_user,
    )
  end
end

app/views/training_periods/_form.html.slim
= simple_form_for(@training_period) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :start
    = f.input :finish
    = f.select :color, (current_user.colors.map {|name, value| [name, value]})

  .form-actions
    = f.button :submit

app/views/training_periods/edit.html.slim
h1 Editing training period

== render 'form'

app/views/training_periods/index.html.slim
h1 Training Periodization

table
  thead
    tr
      th Name
      th Starting on
      th Finishing on
      th Color
      th
      th
      th

  tbody
    - @training_periods.each do |training_period|
      tr
        td = training_period.name
        td = l training_period.start
        td = l training_period.finish
        td = training_period.color
        td = link_to 'Show', training_period
        td = link_to 'Edit', edit_training_period_path(training_period)
        td = link_to 'Destroy', training_period, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Training period', new_training_period_path, class: 'button'

app/views/training_periods/new.html.slim
h1 New training_period

== render 'form'

= link_to 'Back', training_periods_path

app/views/training_periods/show.html.slim
p#notice = notice

p
  strong Name:
  = @training_period.name
p
  strong Start:
  = @training_period.start
p
  strong Finish:
  = @training_period.finish
p
  strong Color:
  = @training_period.color

= link_to 'Edit', edit_training_period_path(@training_period)
'|
= link_to 'Back', training_periods_path