config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
  }

  resources :training_areas
  resources :exercises
  resources :goals
  resources :workouts
  resources :training_periods, path: 'periodization'

  get '/calendar' => 'training#calendar', as: :training_calendar
  get '/motivate' => 'training#motivate', as: :training_motivation
  get '/training' => 'training#index', as: :training
  get '/training/stats' => 'training#stats', as: :training_stats
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="flash flash-#{name.to_s == 'notice' ? 'success' : 'alert'}"
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
header.navigation role="banner"
  .navigation-wrapper
    a.logo href=root_path
      img alt=("Logo Image") src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" /
    a#js-mobile-menu.navigation-menu-button href="javascript:void(0)"  MENU
    nav role="navigation"
      ul#js-navigation-menu.navigation-menu.show
        - if user_signed_in?
          li.nav-link
            = link_to 'Training', training_path
          li.nav-link
            = link_to 'Training Areas', training_areas_path
          li.nav-link
            = link_to 'Exercises', exercises_path
          li.nav-link
            = link_to 'Training Periodization', training_periods_path
          li.nav-link
            = link_to 'Goals', goals_path
          li.nav-link
            = link_to "Settings", edit_user_registration_path
        - else
          li.nav-link.logo
            = link_to 'Venga Bicho!', root_path
    .navigation-tools
      - if user_signed_in?
        = link_to "Sign out", destroy_user_session_path, method: 'delete', class: 'sign-up'
      - else
        a.sign-up href=new_user_registration_path  Sign Up

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title= title
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Weleet'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    - unless @skip_autoloading_assets
      - if Rails.application.config.assets.precompile.include? "#{controller_name}.css"
        == stylesheet_link_tag controller_name, :media => 'all', 'data-turbolinks-track' => true
      - if Rails.application.config.assets.precompile.include? "#{controller_name}.js"
        == javascript_include_tag controller_name, 'data-turbolinks-track' => true

    == yield :head

    == csrf_meta_tags
  body[class="#{controller_name}-#{action_name}"]
    == render 'layouts/navigation'
    == render 'layouts/messages'
    main[role="main"]
      == yield